# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

auto: true # automatically update your jekyll
paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass'] # files to exclude

