# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

auto: true # automatically update your jekyll
paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "css/sass", "README.md"] # files to exclude

