# visit http://jekyllrb.com/docs/configuration/ for more settings
name: Your New Jekyll Site
markdown: redcarpet
highlighter: pygments
paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss', 'bootstrap.scss'] # files to exclude

